name: 12 - Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        description: Build status
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
      output1: ${{ steps.build.outputs.output1 }}
      output2: ${{ steps.build.outputs.output2 }}
    steps:
      - name: Print output path
        run: |
          echo "Output path: $GITHUB_OUTPUT"
      - name: Build
        id: build
        run: |
          echo "Output path: $GITHUB_OUTPUT"
          echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
          echo "output1=value1" >> "$GITHUB_OUTPUT"
          echo "output2=value2" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: |
          echo "Deploying software..."
          echo "output1 = ${{ needs.build.outputs.output1 }}"
          echo "output2 = ${{ needs.build.outputs.output2 }}"
