name: 18 - 1 - Reusable Workflows - Reusable Definition

on:
  workflow_call:
    inputs:
      target-directory:
        type: string
        required: true
    outputs:
      build-status:
        description: The build status
        value: ${{ jobs.deploy.outputs.build-status }}
      url:
        description: The deploy URL
        value: ${{ jobs.deploy.outputs.url }}

jobs:
  deploy:
    outputs:
      build-status: ${{ steps.build.outputs.build-status }}
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
          echo "Building using directory ${{ inputs.target-directory }}"
          echo "Building..."
          echo "build-status=success" >> "$GITHUB_OUTPUT"
      - name: Deploy
        id: deploy
        run: |
          echo "Deploying..."
          echo "url=https://github.com/peterhagelund/foo" >> "$GITHUB_OUTPUT"
