name: 18 - 2 - Resuable Workflows - Reuse Definitions

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflows.yaml
    with:
      target-directory: dummy-dir
  print-outputs:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print outputs
        run: |
          echo "Build status is ${{ needs.deploy.outputs.build-status }}"
          echo "Deploy URL is ${{ needs.deploy.outputs.url }}"
