name: 18 - 3 - Resuable Workflows - Reuse Definitions

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflows.yaml
    with:
      target-directory: dummy-dir
  e2e-tests:
    uses: peterhagelund/gh-actions-course-example-e2e/.github/workflows/e2e.yaml@main
